import Sidebar from './components/Sidebar'
import Sidebar2 from './components/Sidebar2'
import './globals.css'
import '@fortawesome/fontawesome-free/css/all.css';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          {/* <Sidebar2 /> */}
          <Sidebar />
          <div className="w-full px-2 md:pl-64">{children}</div>
      </body>
    </html>
  )
}


{/* <hr className="my-4 md:min-w-full" /> */}